"""add dream11 schema and ml.fixture_poll_schedule

Revision ID: 1acbf07cfb53
Revises: 9fb0900550db
Create Date: 2026-08-18 00:00:00.000000

Like the baseline revision, this is hand-authored, not autogenerated (no
SQLAlchemy ORM models in this project). It captures two pieces of schema
that were applied by hand directly against the dev database, after the
baseline snapshot was taken, and were never recorded in any migration:

- the `dream11` schema (contests, contest_members, player_prices, teams,
  team_players) backing `Game_logic/dream11.py`'s contest/join/team-submit
  endpoints, including its two triggers (`enforce_price_immutability_fn`,
  `enforce_contest_lock_fn`);
- `ml.fixture_poll_schedule`, backing `Game_logic/scheduling.py`'s
  `find_fixtures_needing_poll_schedule` / `mark_fixture_polls_scheduled`.
- `public.users.team_name` (nullable varchar(50)), read/written by
  `Game_logic/team_dashboard.py` and `Context_assembler/main.py` but never
  present in the baseline capture -- running the full test suite against a
  DB built from migrations alone surfaced this immediately (13 failures,
  `column "team_name" does not exist`), which is exactly the kind of drift
  this revision exists to close.

DDL below was captured by introspecting the live dev database directly
(information_schema + pg_get_constraintdef/pg_get_functiondef), the same
approach the baseline used, since pg_dump is not available in this
environment. Column types, defaults, constraints, indexes, and trigger
bodies are reproduced exactly as they exist on the dev database.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1acbf07cfb53'
down_revision: Union[str, Sequence[str], None] = '9fb0900550db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_UPGRADE_SQL = """
CREATE SCHEMA dream11;

CREATE SEQUENCE dream11.contests_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE dream11.contest_members_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE dream11.player_prices_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE dream11.teams_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE dream11.team_players_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE ml.fixture_poll_schedule_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE dream11.contests (
    id integer NOT NULL DEFAULT nextval('dream11.contests_id_seq'::regclass),
    fixture_id integer NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(10) NOT NULL,
    created_by integer NOT NULL,
    max_members smallint NOT NULL DEFAULT 50,
    is_locked boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT contests_pkey PRIMARY KEY (id),
    CONSTRAINT contests_code_key UNIQUE (code),
    CONSTRAINT contests_fixture_id_fkey FOREIGN KEY (fixture_id) REFERENCES ml.fixtures(id) ON DELETE CASCADE,
    CONSTRAINT contests_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE dream11.contest_members (
    id integer NOT NULL DEFAULT nextval('dream11.contest_members_id_seq'::regclass),
    contest_id integer NOT NULL,
    user_id integer NOT NULL,
    joined_at timestamp with time zone DEFAULT now(),
    total_points smallint NOT NULL DEFAULT 0,
    rank smallint NOT NULL DEFAULT 0,
    CONSTRAINT contest_members_pkey PRIMARY KEY (id),
    CONSTRAINT uq_d11_contest_members_contest_user UNIQUE (contest_id, user_id),
    CONSTRAINT contest_members_contest_id_fkey FOREIGN KEY (contest_id) REFERENCES dream11.contests(id) ON DELETE CASCADE,
    CONSTRAINT contest_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE dream11.player_prices (
    id integer NOT NULL DEFAULT nextval('dream11.player_prices_id_seq'::regclass),
    contest_id integer NOT NULL,
    player_id integer NOT NULL,
    credit_price numeric(3,1) NOT NULL,
    CONSTRAINT player_prices_pkey PRIMARY KEY (id),
    CONSTRAINT player_prices_credit_price_check CHECK (((credit_price >= 6.0) AND (credit_price <= 11.0))),
    CONSTRAINT uq_d11_prices_contest_player UNIQUE (contest_id, player_id),
    CONSTRAINT player_prices_contest_id_fkey FOREIGN KEY (contest_id) REFERENCES dream11.contests(id) ON DELETE CASCADE,
    CONSTRAINT player_prices_player_id_fkey FOREIGN KEY (player_id) REFERENCES ml.players(id) ON DELETE CASCADE
);

CREATE TABLE dream11.teams (
    id integer NOT NULL DEFAULT nextval('dream11.teams_id_seq'::regclass),
    contest_id integer NOT NULL,
    user_id integer NOT NULL,
    submitted_at timestamp with time zone DEFAULT now(),
    CONSTRAINT teams_pkey PRIMARY KEY (id),
    CONSTRAINT uq_d11_teams_contest_user UNIQUE (contest_id, user_id),
    CONSTRAINT teams_contest_id_fkey FOREIGN KEY (contest_id) REFERENCES dream11.contests(id) ON DELETE CASCADE,
    CONSTRAINT teams_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE dream11.team_players (
    id integer NOT NULL DEFAULT nextval('dream11.team_players_id_seq'::regclass),
    team_id integer NOT NULL,
    player_id integer NOT NULL,
    is_captain boolean NOT NULL DEFAULT false,
    is_vice_captain boolean NOT NULL DEFAULT false,
    CONSTRAINT team_players_pkey PRIMARY KEY (id),
    CONSTRAINT uq_d11_team_players_team_player UNIQUE (team_id, player_id),
    CONSTRAINT team_players_team_id_fkey FOREIGN KEY (team_id) REFERENCES dream11.teams(id) ON DELETE CASCADE
);

CREATE TABLE ml.fixture_poll_schedule (
    id integer NOT NULL DEFAULT nextval('ml.fixture_poll_schedule_id_seq'::regclass),
    fixture_id integer NOT NULL,
    halftime_scheduled boolean NOT NULL DEFAULT false,
    fulltime_scheduled boolean NOT NULL DEFAULT false,
    scheduled_at timestamp with time zone DEFAULT now(),
    CONSTRAINT fixture_poll_schedule_pkey PRIMARY KEY (id),
    CONSTRAINT uq_fixture_poll_schedule_fixture UNIQUE (fixture_id),
    CONSTRAINT fixture_poll_schedule_fixture_id_fkey FOREIGN KEY (fixture_id) REFERENCES ml.fixtures(id) ON DELETE CASCADE
);

ALTER SEQUENCE dream11.contests_id_seq OWNED BY dream11.contests.id;
ALTER SEQUENCE dream11.contest_members_id_seq OWNED BY dream11.contest_members.id;
ALTER SEQUENCE dream11.player_prices_id_seq OWNED BY dream11.player_prices.id;
ALTER SEQUENCE dream11.teams_id_seq OWNED BY dream11.teams.id;
ALTER SEQUENCE dream11.team_players_id_seq OWNED BY dream11.team_players.id;
ALTER SEQUENCE ml.fixture_poll_schedule_id_seq OWNED BY ml.fixture_poll_schedule.id;

CREATE INDEX idx_d11_contests_fixture ON dream11.contests USING btree (fixture_id);
CREATE INDEX idx_d11_contest_members_contest ON dream11.contest_members USING btree (contest_id);
CREATE INDEX idx_d11_prices_contest ON dream11.player_prices USING btree (contest_id);
CREATE INDEX idx_d11_teams_contest ON dream11.teams USING btree (contest_id);
CREATE INDEX idx_d11_team_players_team ON dream11.team_players USING btree (team_id);

CREATE FUNCTION dream11.enforce_price_immutability_fn() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    RAISE EXCEPTION 'Dream11 player prices are immutable once locked. Cannot UPDATE.';
    RETURN NULL;
END;
$$;

CREATE FUNCTION dream11.enforce_contest_lock_fn() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_locked BOOLEAN;
BEGIN
    SELECT is_locked INTO v_locked FROM dream11.contests WHERE id = NEW.contest_id;
    IF v_locked THEN
        RAISE EXCEPTION 'Contest is locked (fixture has kicked off): contest_id=%', NEW.contest_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER enforce_price_immutability BEFORE UPDATE ON dream11.player_prices FOR EACH ROW EXECUTE FUNCTION dream11.enforce_price_immutability_fn();
CREATE TRIGGER enforce_contest_lock BEFORE INSERT ON dream11.teams FOR EACH ROW EXECUTE FUNCTION dream11.enforce_contest_lock_fn();

ALTER TABLE public.users ADD COLUMN team_name character varying(50);
"""


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(_UPGRADE_SQL)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP SCHEMA dream11 CASCADE")
    op.execute("DROP TABLE IF EXISTS ml.fixture_poll_schedule CASCADE")
    op.execute("ALTER TABLE public.users DROP COLUMN IF EXISTS team_name")
