"""baseline capture hand-applied schema

Revision ID: 9fb0900550db
Revises:
Create Date: 2026-08-15 18:46:56.677958

This is a hand-authored baseline, not an autogenerated one -- this project
has no SQLAlchemy ORM models (every module uses raw SQL / SQLAlchemy Core),
so `alembic revision --autogenerate` has nothing to diff against.

upgrade() replays the exact schema-only DDL captured from the live database
via `pg_dump --schema-only --schema=ml --schema=public --no-owner
--no-privileges` (see baseline_schema.sql next to this file), so every
table, column, default, sequence, constraint, index (including the partial
unique index on chips), trigger, and trigger function is reproduced exactly
as it existed on the hand-applied database -- not reconstructed from code
comments, which were confirmed to be incomplete (two trigger functions,
ml.enforce_player_identity_fn and ml.enforce_ml_prediction_immutability_fn,
are not referenced anywhere in the Python codebase and were only found by
querying the live database directly).

Two lines were stripped from the raw pg_dump output before embedding here:
- `\\restrict` / `\\unrestrict` -- psql-only meta-commands (Postgres 18
  dump-integrity markers), not valid SQL, would error over a raw DBAPI
  connection.
- `CREATE SCHEMA public;` / its COMMENT -- `public` already exists in any
  freshly created Postgres database (from template1), so re-creating it
  would fail with "schema already exists".
"""
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb0900550db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_BASELINE_SQL_PATH = Path(__file__).resolve().parent.parent / "baseline_schema.sql"

_PUBLIC_TABLES = [
    "leaderboard_snapshots",
    "league_h2h_fixtures",
    "league_members",
    "transfers",
    "chips",
    "starting_xi",
    "gw_scores",
    "gw_selections",
    "squad_players",
    "user_squads",
    "mini_leagues",
    "users",
]


def upgrade() -> None:
    """Upgrade schema."""
    sql = _BASELINE_SQL_PATH.read_text(encoding="utf-8")
    op.execute(sql)


def downgrade() -> None:
    """Downgrade schema."""
    # ml schema: drop everything in it (tables, sequences, functions,
    # triggers all go with CASCADE) then the schema itself.
    op.execute("DROP SCHEMA ml CASCADE")

    # public is Postgres's default schema and must not be dropped outright --
    # only drop the tables (and their owned sequences/triggers/indexes via
    # CASCADE) that this migration created, in FK-safe order (children first).
    for table in _PUBLIC_TABLES:
        op.execute(f"DROP TABLE IF EXISTS public.{table} CASCADE")

    for fn in (
        "enforce_chip_limit_fn",
        "enforce_selection_lock_fn",
        "enforce_snapshot_immutability_fn",
        "enforce_transfers_immutability_fn",
    ):
        op.execute(f"DROP FUNCTION IF EXISTS public.{fn}() CASCADE")
